Updated README.MD
Updated README.MD changing 'user' within require to `users` to resolve:
```
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'admin-bro-user-permissions/policies/isAccessGranted'
```